### ISSUE TITLE
Document design for transport::VSomeIpUTransport

### ISSUE THREAD

**Issue by gregmedd** [eclipse-uprotocol/up-transport-vsomeip-cpp#4]
This should cover anything extra being done to support the SOME/IP transport. Are additional threads required? Or a thread pool? Any locking needed? Will this implementation be doing anything special based on message type (e.g. modifying messages, operating in specific modes based on message type, etc.)? If so, how will that be done?

**Comment by pranavishere2** [comment]
As discussed,
This task is not a single person task and need a breakdown. I will work on this issue so for tracking purpose you can assign this task to me.

**Comment by ruchirchauhan** [comment]
I shall be contributing to this task as well
